#!/bin/bash
#
# Title:      PGBlitz (Reference Title File)
# Author(s):  Admin9705
# URL:        https://pgblitz.com - http://github.pgblitz.com
# GNU:        General Public License v3.0
################################################################################
---
- hosts: localhost
  gather_facts: false
  tasks:

# INFO: Version Number 900 for example is 9.0.0 or 9110 would be 9.1.10; in most
# cases, this is updated very little unless forcing a change in the stager

    - name: Cloning PG Blitz v9
      git:
        repo: "https://github.com/hawk2g/PGBlitz.com"
        dest: /pg/pgblitz
        version: "v90"
        force: yes
